apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lime-mysql-pv-claim
  namespace: przemek
  labels:
    app: limesurvey-mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 300M
	  