apiVersion: v1
kind: Service
metadata:
  name: limesurvey-mysql
  namespace: przemek
  labels:
    app: limesurvey-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: limesurvey-mysql
	