apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lime-pv-claim
  namespace: przemek
  labels:
    app: limesurvey-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500M
	  