apiVersion: v1
kind: Service
metadata:
  name: limesurvey-web
  namespace: przemek
  labels:
    app: limesurvey-web
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    targetPort: 8080
    protocol: TCP
  selector:
    app: limesurvey-web