apiVersion: apps/v1
kind: Deployment
metadata:
  name: limesurvey-web
  namespace: przemek
  labels:
    app: limesurvey-web
spec:
  selector:
    matchLabels:
      app: limesurvey-web
  template:
    metadata:
      labels:
        app: limesurvey-web
    spec:
      containers:
      - image: wordpress:php8.0-apache
        name: limesurvey-web
        env:
        - name: WORDPRESS_DB_HOST
          value: limesurvey-mysql
        - name: WORDPRESS_DB_NAME
          value: limesurvey_db
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: onlyDevelopment
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1024Mi"
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
        - name: limesurvey-persistent-storage
          mountPath: /var/www/html        
      volumes:
      - name: limesurvey-persistent-storage
        persistentVolumeClaim:
          claimName: lime-pv-claim
		  